# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_merchant_mollie}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edwin Vlieg"]
  s.date = %q{2010-04-18}
  s.description = %q{ActiveMerchant extension to support the Dutch PSP Mollie with iDeal transactions}
  s.email = %q{info@moneybird.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/active_merchant/billing/mollie_ideal.rb",
     "lib/active_merchant/billing/mollie_ideal_check_response.rb",
     "lib/active_merchant/billing/mollie_ideal_fetch_response.rb",
     "lib/active_merchant_mollie.rb"
  ]
  s.homepage = %q{http://github.com/bluetools/active_merchant_mollie}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ActiveMerchant extension to support the Dutch PSP Mollie with iDeal transactions}
  s.test_files = [
    "spec/mollie_ideal_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<active_merchant>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
    else
      s.add_dependency(%q<active_merchant>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
    end
  else
    s.add_dependency(%q<active_merchant>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
  end
end

